name: Build and Push to Container Registries

on:
  push:
    branches:
      - master

env:
  GITHUB_SHA: ${{ github.sha }}
  BRANCH: ${{ github.ref }}
  DOCKERHUB_OWNER: covidmongolia
  DOCKERHUB_REPO: backend-server

jobs:
  build-n-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u $DOCKERHUB_OWNER --password-stdin

      - name: Build & Push Key Retrieval
        env:
          COMPONENT: key-retrieval
        run: |
          docker build --build-arg branch=$BRANCH --build-arg revision=$GITHUB_SHA --build-arg component=$COMPONENT \
          -t $DOCKERHUB_OWNER/$DOCKERHUB_REPO:$COMPONENT-$GITHUB_SHA \
          -t $DOCKERHUB_OWNER/$DOCKERHUB_REPO:$COMPONENT-latest .
          docker push $DOCKERHUB_OWNER/$DOCKERHUB_REPO:$COMPONENT-$GITHUB_SHA
          docker push $DOCKERHUB_OWNER/$DOCKERHUB_REPO:$COMPONENT-latest

      - name: Build & Push Key Submission
        env:
          COMPONENT: key-submission
        run: |
          docker build --build-arg branch=$BRANCH --build-arg revision=$GITHUB_SHA --build-arg component=$COMPONENT \
          -t $DOCKERHUB_OWNER/$DOCKERHUB_REPO:$COMPONENT-$GITHUB_SHA \
          -t $DOCKERHUB_OWNER/$DOCKERHUB_REPO:$COMPONENT-latest .
          docker push $DOCKERHUB_OWNER/$DOCKERHUB_REPO:$COMPONENT-$GITHUB_SHA
          docker push $DOCKERHUB_OWNER/$DOCKERHUB_REPO:$COMPONENT-latest
