name: Testing Go CI
on:
  - push
  - pull_request

jobs:
  testing:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14'
    - name: Run Go tests
      run: |
        go test ./pkg/... -cover
